POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Сырники из творога",
  "cookingTime": 30,
  "ingredients": [

  ],
  "steps": [
    "1. Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте.",
    "2. Всыпьте в творог муку и тщательно перемешайте.",
    "3. Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.",
    "4. Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду.",
    "5. Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния.",
    "6. Повторяйте, пока творог не закончится."
  ]
}
###
GET http://localhost:8080/recipe/1
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом",
  "cookingTime": 7,
  "ingredients": [

  ],
  "steps": [
    "1. Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой.",
    "2. Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром.",
    "3. Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."
  ]
}
###
GET http://localhost:8080/recipe/2
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Чечевичный суп с мятой",
  "cookingTime": 30,
  "ingredients": [

  ],
  "steps": [
    "1. В небольшую кастрюлю налить литр воды и засыпать промытую чечевицу. Поставить кастрюлю на средний огонь.",
    "2. Натереть небольшую морковь на крупной терке, мелко нарезать лук. Как только чечевица начнет кипеть, надо убавить огонь, а затем долить еще 200 мл воды или бульона. Варить еще десять минут.",
    "3. Разогреть широкую плоскую сковороду, добавить туда подсолнечное и сливочное масло. Обжарить лук и морковь.",
    "4. Добавить обжаренные овощи в кастрюлю, влить сливки. Взбить суп ручным блендером, чтобы он превратился в густое пюре. Суп можно подавать к столу."
  ]
}
###
GET http://localhost:8080/recipe/3